name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate project structure and imports
      run: |
        pytest tests/integration/test_pipeline.py -k "test_project_structure or test_imports" --disable-warnings

    - name: Run pipeline test
      run: |
        pytest tests/integration/test_pipeline.py -k "test_pipeline" --disable-warnings
